SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
SERVER_NAME = "corozcoS"
WORKER_NAME = "corozcoSW"
TOKEN_FILE = "/vagrant/node-token"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 3
  end

  def common_provision(control)
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y net-tools
    SHELL
  end

  config.vm.define "#{SERVER_NAME}" do |control|
    control.vm.hostname = "#{SERVER_NAME}"
    control.vm.network "private_network", ip: "#{SERVER_IP}"
    common_provision(control)
    
    control.vm.provision "shell", inline: <<-SHELL
      # Provisión específica para corozcoS
      # Agregar tus comandos personalizados aquí
      sudo ip link add eth1 type dummy
      sudo ip addr add 192.168.56.110/24 dev eth1
      sudo ip link set eth1 up

      # Instalar K3s en modo controlador
      alias k="sudo kubectl"
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-init --node-ip #{SERVER_IP}" sh -
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant
    SHELL
  end

  config.vm.define "#{WORKER_NAME}" do |control|
    control.vm.hostname = "#{WORKER_NAME}"
    control.vm.network "private_network", ip: "#{WORKER_IP}"
    common_provision(control)
    
    control.vm.provision "shell", inline: <<-SHELL
      # Provisión específica para corozcoSW
      # Agregar tus comandos personalizados aquí
      sudo ip link add eth1 type dummy
      sudo ip addr add 192.168.56.111/24 dev eth1
      sudo ip link set eth1 up
      # Imprimir el contenido del archivo de token
      cat #{TOKEN_FILE}
      # https://blog.programster.org/install-k3s-agent-on-ubuntu-20-04
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://#{SERVER_IP}:6443 --token-file #{TOKEN_FILE} --node-ip=#{WORKER_IP}" sh -s -
    SHELL
  end
end
