Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  def common_provision(control)
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      alias k="sudo kubectl"
    SHELL
  end

  config.vm.define "corozcoS" do |control|
    control.vm.hostname = "corozcoS"
    control.vm.network "private_network", ip: "192.168.56.110"
    common_provision(control)
    
    control.vm.provision "shell", inline: <<-SHELL
      # Provisión específica para corozcoS
      # Agregar tus comandos personalizados aquí
    SHELL
  end

  config.vm.define "corozcoSW" do |control|
    control.vm.hostname = "corozcoSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    common_provision(control)

    control.vm.provision "shell", inline: <<-SHELL
      # Provisión específica para corozcoSW
      # Agregar tus comandos personalizados aquí
    SHELL
  end
end
