SERVER_IP = "192.168.56.110"
SERVER_NAME = "corozcoS"
PATH_YAML = "/vagrant/srcs/app/"
PATH_CONFIGMAP_YAML = "/vagrant/srcs/configmap/"
PATH_INGRESS = "/vagrant/srcs/ingress/"


$serverscript = <<-SCRIPT
apt-get update
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-init --node-ip #{SERVER_IP}" sh -
kubectl apply -f #{PATH_YAML}
SCRIPT

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
  end

  config.vm.define "#{SERVER_NAME}" do |control|
    control.vm.hostname = "#{SERVER_NAME}"
    control.vm.network "private_network", bridge: "enp0s8", ip: "#{SERVER_IP}"
    control.vm.provision "shell", inline: $serverscript
  end
end
