SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
SERVER_NAME = "corozcoS"
WORKER_NAME = "corozcoSW"
TOKEN_FILE = "/vagrant/node-token"

# Initialize a new cluster using etcd specifying the node's advertising address 
# Copy the node-token to the host machine
$serverscript = <<-SCRIPT
apt-get update
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-init --node-ip #{SERVER_IP}" sh -
cp /var/lib/rancher/k3s/server/node-token /vagrant
SCRIPT

# Join the cluster with token file, and specify the node's advertising address
$nodescript = <<-SCRIPT
apt-get update
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://#{SERVER_IP}:6443 --token-file #{TOKEN_FILE} --node-ip=#{WORKER_IP}" sh -s -
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "#{SERVER_NAME}" do |control|
    control.vm.hostname = "#{SERVER_NAME}"
    control.vm.network "private_network", bridge: "enp0s8", ip: "#{SERVER_IP}"

    # Install K3s on server machine
    control.vm.provision "shell", inline: $serverscript
  end

  config.vm.define "#{WORKER_NAME}" do |control|
    control.vm.hostname = "#{WORKER_NAME}"
    control.vm.network "private_network", bridge: "enp0s8", ip: "#{WORKER_IP}"

    # Install K3s on worker machine
    control.vm.provision "shell", inline: $nodescript
  end
end
